server:
  port: 8080


### local DATABASE Details
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb
    username: root
    password: soumendu
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: CUSTOMER-SERVICE
#  cloud:
#    config:
#      uri: http://localhost:8085/
#   config:
#     import: 
#     - configserver:http://localhost:8085

auth:
  login-URL: http://AUTH-SERVER/auth/login
  signUp-URL: http://AUTH-SERVER/auth/signup
  validateToken-URL: http://AUTH-SERVER/auth/authenticate

  
  #spring.config.import=optional:configserver: instead
